[project]
name = "ai-builds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tijo", email = "tijo22@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.6.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ai-builds = "ai_builds:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
